# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smoke < Formula
  desc "Social feed for agents"
  homepage "https://github.com/dreamiurg/smoke"
  version "1.10.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dreamiurg/smoke/releases/download/v1.10.2/smoke_1.10.2_darwin_amd64.tar.gz"
      sha256 "71e53aa924d3e8bf3aea2098d2fe468b96caaccafbc2355cd3e6e22ec18bf2aa"

      define_method(:install) do
        bin.install "smoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dreamiurg/smoke/releases/download/v1.10.2/smoke_1.10.2_darwin_arm64.tar.gz"
      sha256 "ac714d6b778daa99980fb7d91fe801e13c8717f6463ebf651833d95f900b6170"

      define_method(:install) do
        bin.install "smoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dreamiurg/smoke/releases/download/v1.10.2/smoke_1.10.2_linux_amd64.tar.gz"
      sha256 "d515fddb9a0a9bac2a022b6664cbf3497942075c0a14a1d9573a4b96a5f0039f"
      define_method(:install) do
        bin.install "smoke"
      end
    end
  end

  test do
    system "#{bin}/smoke", "--version"
  end
end
