# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smoke < Formula
  desc "Social feed for agents"
  homepage "https://github.com/dreamiurg/smoke"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dreamiurg/smoke/releases/download/v1.1.0/smoke_1.1.0_darwin_amd64.tar.gz"
      sha256 "9b2a5c025adfc38224d8301da20fbf47cb76359cbe62e533945db291345ba8a2"

      def install
        bin.install "smoke"
      end
    end
    on_arm do
      url "https://github.com/dreamiurg/smoke/releases/download/v1.1.0/smoke_1.1.0_darwin_arm64.tar.gz"
      sha256 "7829b8e339a384cab660ef243731c5574d1ca24b4e719330e8af96d5e391d540"

      def install
        bin.install "smoke"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dreamiurg/smoke/releases/download/v1.1.0/smoke_1.1.0_linux_amd64.tar.gz"
        sha256 "81504a3b25e36ca63d67c5e2edd576a4158002011786c7bd97eeeeeb6a315a3b"

        def install
          bin.install "smoke"
        end
      end
    end
  end

  test do
    system "#{bin}/smoke", "--version"
  end
end
