# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smoke < Formula
  desc "Social feed for agents"
  homepage "https://github.com/dreamiurg/smoke"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dreamiurg/smoke/releases/download/v1.3.0/smoke_1.3.0_darwin_amd64.tar.gz"
      sha256 "cec07720296e3081a54680c90615fca1846b1ea281362c906c0f7a5ce9e5d244"

      def install
        bin.install "smoke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dreamiurg/smoke/releases/download/v1.3.0/smoke_1.3.0_darwin_arm64.tar.gz"
      sha256 "4d4ad6f4471f29fdd44a5a37ef0de4b747d270b7d69b29389a342331da9f5c67"

      def install
        bin.install "smoke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dreamiurg/smoke/releases/download/v1.3.0/smoke_1.3.0_linux_amd64.tar.gz"
      sha256 "57fde2c03f75309051c2c6cbdedb285519aaa567b6d59d53ccfd4a309de9dc7a"
      def install
        bin.install "smoke"
      end
    end
  end

  test do
    system "#{bin}/smoke", "--version"
  end
end
